/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2a3232",
        "on-primary-container": "#006b71",
        "tertiary-container": "#f1d1ff",
        "surface-container-high": "#232b2c",
        "on-secondary": "#5b005b",
        "secondary": "#ffabf3",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "surface-dim": "#0d1515",
        "primary-container": "#00f3ff",
        "surface-container-highest": "#2e3637",
        "on-tertiary-container": "#9500df",
        "primary": "#e3fdff",
        "surface": "#0d1515",
        "on-secondary-container": "#500050",
        "primary-fixed-dim": "#00dce6",
        "on-primary-fixed-variant": "#004f53",
        "surface-tint": "#00dce6",
        "primary-fixed": "#6ff6ff",
        "secondary-fixed": "#ffd7f5",
        "inverse-primary": "#00696f",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#e5b5ff",
        "on-tertiary-fixed": "#30004b",
        "background": "#0d1515",
        "on-secondary-fixed": "#380038",
        "outline": "#849495",
        "on-secondary-fixed-variant": "#810081",
        "on-tertiary-fixed-variant": "#7000a8",
        "surface-bright": "#333b3b",
        "on-primary-fixed": "#002022",
        "on-primary": "#00373a",
        "secondary-fixed-dim": "#ffabf3",
        "tertiary": "#fff6fd",
        "secondary-container": "#fe00fe",
        "error-container": "#93000a",
        "tertiary-fixed": "#f4d9ff",
        "on-surface-variant": "#b9cacb",
        "outline-variant": "#3a494b",
        "surface-container": "#192122",
        "surface-container-low": "#151d1e",
        "surface-variant": "#2e3637",
        "inverse-surface": "#dce4e4",
        "on-tertiary": "#4e0078",
        "on-background": "#dce4e4",
        "surface-container-lowest": "#081010",
        "on-surface": "#dce4e4",
        // preserve current app colors just in case
        appPrimary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        }
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-lg": "80px",
        "margin-md": "40px",
        "unit": "8px",
        "margin-sm": "16px"
      },
      fontFamily: {
        "headline-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "label-mono": ["Space Mono"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"]
      },
      fontSize: {
        "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-mono": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}]
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
